add @Nonnull for find problem
Cannot invoke "java.lang.Runnable.run()" because "updater" is null: Cannot invoke "java.lang.Runnable.run()" because "updater" is null
java.lang.NullPointerException: Cannot invoke "java.lang.Runnable.run()" because "updater" is null
	at consulo/consulo.language.inject.advanced.api@3-SNAPSHOT/consulo.language.inject.advanced.ui.AbstractInjectionPanel.updateTree(AbstractInjectionPanel.java:173)